// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVrx8mwGKdf4PERSbOkAR4jOdKpaf4Q6Y',
    appId: '1:558181251435:web:79d8951f0d89552b11742e',
    messagingSenderId: '558181251435',
    projectId: 'carpool-8d602',
    authDomain: 'carpool-8d602.firebaseapp.com',
    storageBucket: 'carpool-8d602.appspot.com',
    measurementId: 'G-XZF1MS0ZJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkFClCV051OW7Uc_WEd38EU_xMOM5ejGg',
    appId: '1:558181251435:android:d4ae3774d160562e11742e',
    messagingSenderId: '558181251435',
    projectId: 'carpool-8d602',
    storageBucket: 'carpool-8d602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6p_ViCh3xtKPzpKj7ae80rBKP_MhnxTQ',
    appId: '1:558181251435:ios:7b839d6173f78b4311742e',
    messagingSenderId: '558181251435',
    projectId: 'carpool-8d602',
    storageBucket: 'carpool-8d602.appspot.com',
    iosClientId: '558181251435-3lc09tseb9tnhogvor9ddmq8trin607q.apps.googleusercontent.com',
    iosBundleId: 'com.example.carpool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6p_ViCh3xtKPzpKj7ae80rBKP_MhnxTQ',
    appId: '1:558181251435:ios:7b839d6173f78b4311742e',
    messagingSenderId: '558181251435',
    projectId: 'carpool-8d602',
    storageBucket: 'carpool-8d602.appspot.com',
    iosClientId: '558181251435-3lc09tseb9tnhogvor9ddmq8trin607q.apps.googleusercontent.com',
    iosBundleId: 'com.example.carpool',
  );
}
